add Apache Kylin index
byzer-org/byzer-lang pull request #1414
Opened 2021-03-31 03:23 UTC by liuyonghengheng

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-03-31 03:35 UTC, allwefantasy commented
能够简要描述下改写逻辑么？

2021-03-31 03:46 UTC, allwefantasy requested changes

2021-03-31 03:46 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdown.scala
> +      if (l.jdbcOptions.url.toLowerCase.startsWith("jdbc:mysql:"))
jdbc option 不应该是 jdbc:kylin么？

2021-03-31 03:47 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdown.scala
> +      if (l.jdbcOptions.url.toLowerCase.startsWith("jdbc:mysql:"))
我现在为了方便，直接查的mysql，逻辑上是一样的

2021-03-31 03:48 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdown.scala
> +      if (l.jdbcOptions.url.toLowerCase.startsWith("jdbc:mysql:"))
为了方便测试

2021-03-31 03:48 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdown.scala
> +      if (l.jdbcOptions.url.toLowerCase.startsWith("jdbc:mysql:"))
你可以本地起一个kylin的docker；mlsql默认已经集成kylin的driver.

2021-03-31 03:56 UTC, allwefantasy requested changes

2021-03-31 03:56 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdown.scala
> +      if (l.jdbcOptions.tableOrQuery.toLowerCase.startsWith("select"))
这里可以直接  `l.jdbcOptions.tableOrQuery.toLowerCase.startsWith("select")`

2021-03-31 03:56 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/tech/mlsql/plugins/sql/profiler/QueryIndexerPlugin.scala
> +//    if (!params.getOrElse("enableQueryWithIndexer", "false").toBoolean) {
这些代码要注释回来哈。

2021-03-31 04:09 UTC, liuyonghengheng commented
添加Kylin index

- 添加逻辑如下

目前处理逻辑比较简单，只会在子查询匹配为 SubqueryAlias(Aggregate(Filter(SubqueryAlias(Project(LogicalRelation(JDBCRelation)))) 的情况下，才会把子查询 直接下压到数据源。

 1. 匹配规则为 SubqueryAlias->Aggregate->Filter->SubqueryAlias->Project->LogicalRelation->JDBCRelation
 2. 判断 关系是否是否为 JDBCRelation 并且 url 前缀为 jdbc:kylin:  并且 tableOrQuery 内容是一个表,而不是查询,如果处理查询会非常复杂,目前先不考虑。
 3. 对于匹配的子查询进行简单的转换，目前做的主要是 去除 cast 表达式
 4. 生成子查询逻辑的查询语句
 5. 生成新的LogicalRelation，和子查询SubqueryAlias 
 6. 替换ExprId，新生成的子查询中的 所有的属性 id替换为老的id

- 注意
为了方便测试，目前是使用 mysql作为数据源，逻辑和直接连kylin是一样的
有些地方为了测试方便直接 注释掉了

- 问题如下
1. resolved 问题，修改查询计划之后会出现部分计划 resolved  false的问题，导致在生成sql时无法通过 LogicalPlanSQL 中的 require(plan.resolved, "LogicalPlan must be resolved.") 检查
2. 虽然查询计划已经修改，但是最终并没有下压成功，IndexerPlugin 中 生成的finalLP 是正确的，但是最后并没有下压 LogicalRelation 中的查询

2021-03-31 04:10 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/tech/mlsql/plugins/sql/profiler/QueryIndexerPlugin.scala
> +//    if (!params.getOrElse("enableQueryWithIndexer", "false").toBoolean) {
OK

2021-03-31 07:31 UTC, allwefantasy commented
> 添加Kylin index
> 
> * 添加逻辑如下
> 
> 目前处理逻辑比较简单，只会在子查询匹配为 SubqueryAlias(Aggregate(Filter(SubqueryAlias(Project(LogicalRelation(JDBCRelation)))) 的情况下，才会把子查询 直接下压到数据源。
> 
> 1. 匹配规则为 SubqueryAlias->Aggregate->Filter->SubqueryAlias->Project->LogicalRelation->JDBCRelation
> 2. 判断 关系是否是否为 JDBCRelation 并且 url 前缀为 jdbc:kylin:  并且 tableOrQuery 内容是一个表,而不是查询,如果处理查询会非常复杂,目前先不考虑。
> 3. 对于匹配的子查询进行简单的转换，目前做的主要是 去除 cast 表达式
> 4. 生成子查询逻辑的查询语句
> 5. 生成新的LogicalRelation，和子查询SubqueryAlias
> 6. 替换ExprId，新生成的子查询中的 所有的属性 id替换为老的id
> 
> * 测试的查询语句如下，使用mlsql 的元数据表 mlsql_console.mlsql_job 做测试
> 
> ```
>  load jdbc.`mlsql_console.mlsql_job`  where url="jdbc:mysql://localhost/mlsql_console?user=root&password=Hadoop-123" 
> as test_mlsql1;
> 
> select ss,mlsql_user_id from (select sum(status) as ss ,mlsql_user_id from test_mlsql1 where id=1 and mlsql_user_id=1 group by mlsql_user_id) t1 as test_mlsql1_delta;
> ```
> 
> * 注意
>   为了方便测试，目前是使用 mysql作为数据源，逻辑和直接连kylin是一样的
>   有些地方为了测试方便直接 注释掉了
> * 问题如下
> 
> 1. resolved 问题，修改查询计划之后会出现部分计划 resolved  false的问题，导致在生成sql时无法通过 LogicalPlanSQL 中的 require(plan.resolved, "LogicalPlan must be resolved.") 检查
> 2. 虽然查询计划已经修改，但是最终并没有下压成功，IndexerPlugin 中 生成的finalLP 是正确的，但是最后并没有下压 LogicalRelation 中的查询

目前你对Spark LP 的使用还不够到位，而且你设置的匹配规则显然太窄，譬如下面的最简单的语句都无法匹配：

```mlsql
 load jdbc.`db_1.mlsql_indexer` as mlsql_jobs;
 
 select a.* from (select id,sum(sync_interval) from mlsql_jobs group by id ) as a as output;
```

实际上`select id,sum(sync_interval) from mlsql_jobs group by id ` 是完全可以整个下推给Kylin的。

实际的匹配规则应该是采用transformUp，对遇到的每一个subquery, 检测其是不是只包含 Kylin的JdbcRelation，如果是，再检测是否包含agg, 如果还是，那么确定可以整个下推给kylin执行。否则就无需再网上走了。因为up之上的显然不会满足条件。

2021-03-31 08:00 UTC, allwefantasy commented
我这里写了一个示例：

```scala
def pushdown3(lp: LogicalPlan): LogicalPlan = {
    val attributeMapping = mutable.HashMap[Attribute,Attribute]()

    val newlp = lp transformDown {
      case suba1@SubqueryAlias(_, _) =>


        var lastTable:LogicalRelation = null
        val tables = ArrayBuffer[LogicalRelation]()
        suba1 transformAllExpressions {
          case lr@LogicalRelation(_, _, _, _) =>
            tables += lr
            lastTable = lr
            lr

        }

        //检测所有涉及到的表是不是都是kylin表,最好能再检测下是不是都是一个kylin实例
        val nonJDBCTablesNum = tables.filterNot(lr1 => isKylinJDBCRelation(lr1.relation) && isQueryTable(lr1.relation)).length
        if (nonJDBCTablesNum > 0) return suba1

        //检测是否有agg,如果是，那么可以下推
        var aggExits = false
        suba1 transformDown {
          case a@Aggregate(_,_,_)=>
            aggExits = true
            a
        }

        if(!aggExits) return suba1

        // 获取子query的所有输出
        val attributes = suba1.output

        //将子树转化成sql进行下推
        val newsubalp = new LogicalPlanSQL(suba1, new KylinSQLDialect)

        val directoryQuery = newsubalp.toSQL
        logInfo(s"push down query: ${directoryQuery}")

        //此处，我们只考虑一个kylin实例的情况。多个实例混合，单独处理。
        val newr = KylinPushdown.createRelationFromOld(directoryQuery, lastTable.relation)
        val newlr = LogicalRelation(newr)
        // 整个subquery 都会被替换成这个newr 
        attributes.zip(newlr.output).foreach{case (a,b)=>
          attributeMapping += (a->b)
        }
        newlr

    }
    // 使用 attributeMapping 修正 newlp 所有引用,这里我就不写了
    newlp
  }
```

另外，测试完成后，要好好整理下代码 😁

2021-03-31 10:16 UTC, liuyonghengheng commented
感谢大佬指点，还有那么完整详细的示例子-重写。现在的主要问题是虽然最终的逻辑是对的，但是实际上从 mysql的查询日志来看，并没有真正的把 聚合下压到mysql，包括修改前的和修改后的逻辑都是最终无法实现聚合下压

2021-03-31 12:53 UTC, allwefantasy commented
> 感谢大佬指点，还有那么完整详细的示例子-重写。现在的主要问题是虽然最终的逻辑是对的，但是实际上从 mysql的查询日志来看，并没有真正的把 聚合下压到mysql，包括修改前的和修改后的逻辑都是最终无法实现聚合下压

你从哪里看出来没有下压？

2021-04-01 00:47 UTC, allwefantasy commented
> 感谢大佬指点，还有那么完整详细的示例子-重写。现在的主要问题是虽然最终的逻辑是对的，但是实际上从 mysql的查询日志来看，并没有真正的把 聚合下压到mysql，包括修改前的和修改后的逻辑都是最终无法实现聚合下压

是RestController接口的Bug.

2021-04-01 02:08 UTC, liuyonghengheng commented
> > 感谢大佬指点，还有那么完整详细的示例子-重写。现在的主要问题是虽然最终的逻辑是对的，但是实际上从 mysql的查询日志来看，并没有真正的把 聚合下压到mysql，包括修改前的和修改后的逻辑都是最终无法实现聚合下压
> 
> 是RestController接口的Bug.

根据大佬的修改，对应的pr是这个：[关联pr](https://github.com/allwefantasy/mlsql/pull/1415)

2021-04-12 06:21 UTC, liuyonghengheng commented
新的PR 已更改为 更为通用的下压方案，目前可以实现mysql 和apache kylin的下压。

### 聚合下压新设计

1. 首先需要使用递归的方式，从叶子结点开始遍历逻辑计划树，给所有的节点打标签，重新构建一颗标签树，内容包括：数据源类型，数据库，能否下压
   1. 判断是否为叶子结点，如果是叶子结点则生成对应的标签，并判断能否下压，
   2. 不是叶子结点的，需要先判断孩子结点是否可以下压，如果可以则判断本结点是否可以下压
   3. 重复以上步骤直到标记整棵树
2. 遍历 标签树，挑出所有能够下压的最上层结点
3. 进行逻辑替换

#### 参数说明

connect/load jdbc 时可以指定参数 ispushdown

default: "false"

默认是不开启下压，使用方式参考下面的测试用例

#### 测试用例



```sql

-- 测试用例：

---------------------- create mysql db -----------------

create database learn_kylin;
GRANT ALL PRIVILEGES ON learn_kylin.* TO 'root'@'%' WITH GRANT OPTION ;
FLUSH PRIVILEGES;

use learn_kylin;

create table kylin_sales_my1 (
BUYER_ID bigint,
OPS_REGION varchar(256),
price decimal(19,4)
);

create table kylin_sales_my2 (
BUYER_ID bigint,
OPS_REGION varchar(256),
price decimal(19,4)
);

insert into kylin_sales_my1 values(10000152,"Hongkong",60.1746)
,(10000015,"Shanghai",0.155)
,(10000017,"Beijing",13.1225)
,(10000027,"Shanghai",86.2841)
,(10000066,"Hongkong",83.3488)
,(10000175,"Hongkong",31.4514)
,(10000172,"Beijing",30.7342)
,(10000074,"Beijing",88.0112)
,(10000056,"Beijing",5.3982)
,(10000116,"Hongkong",9.8382);


insert into kylin_sales_my2 values(10000152,"Hongkong",60.1746)
,(10000015,"Shanghai",0.155)
,(10000017,"Beijing",13.1225)
,(10000027,"Shanghai",86.2841)
,(10000066,"Hongkong",83.3488)
,(10000175,"Hongkong",31.4514)
,(10000172,"Beijing",30.7342)
,(10000074,"Beijing",88.0112)
,(10000056,"Beijing",5.3982)
,(10000116,"Hongkong",9.8382);

----------------------- test mysql ---------------------

-- 简单测试

connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpassword"
and ispushdown="true"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;

select BUYER_ID,sum(price) as ss, count(1) as cc from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID as output;

select BUYER_ID,sum(price), count(1) from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID as output;

select BUYER_ID,sum(price) as ss, count(1) as cc from kylin_sales_my1 group by BUYER_ID as output;

-- 默认不下压
connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpassword"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;
load jdbc.`db_1.kylin_sales_my2` as kylin_sales_my2;

select t1.BUYER_ID, t1.ss, t2.ss as s2 from 
(select BUYER_ID,sum(price) as ss from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID) t1 
join 
(select BUYER_ID,sum(price) as ss from kylin_sales_my2 group by BUYER_ID) t2 
on t1.BUYER_ID=t2.BUYER_ID 
as output;

-- 全部下压
connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpassword"
and ispushdown="true"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;
load jdbc.`db_1.kylin_sales_my2` as kylin_sales_my2;

select t1.BUYER_ID, t1.ss, t2.ss as s2 from 
(select BUYER_ID,sum(price) as ss from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID) t1 
join 
(select BUYER_ID,sum(price) as ss from kylin_sales_my2 group by BUYER_ID) t2 
on t1.BUYER_ID=t2.BUYER_ID 
as output;

-- 部分下压
connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpassword"
and ispushdown="true"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;
load jdbc.`db_1.kylin_sales_my2` where ispushdown="false" as kylin_sales_my2;

select t1.BUYER_ID, t1.ss, t2.ss as s2 from 
(select BUYER_ID,sum(price) as ss from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID) t1 
join 
(select BUYER_ID,sum(price) as ss from kylin_sales_my2 group by BUYER_ID) t2 
on t1.BUYER_ID=t2.BUYER_ID 
as output;

----------------------- test kylin ----------------------
-- kylin 测试

connect jdbc where
url="jdbc:kylin://localhost:7070/learn_kylin"
and driver="org.apache.kylin.jdbc.Driver"
and user="ADMIN"
and password="KYLIN"
and ispushdown="true"
as db_2;

load jdbc.`db_2.KYLIN_SALES` as kylin_sales_t;

--select count(1) as c from kylin_sales_t as t1;

--select sum(price) as s from kylin_sales_t as t2;

--select sum(price) as s, count(1) as c, BUYER_ID from kylin_sales_t group by BUYER_ID limit 10 as t3;

select sum(price) as s, count(1) as c, BUYER_ID from kylin_sales_t where BUYER_ID=10001779  group by BUYER_ID as t4;

--------------------- test kylin join mysql --------------

connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpassword"
and ispushdown="true"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;

connect jdbc where
url="jdbc:kylin://localhost:7070/learn_kylin"
and driver="org.apache.kylin.jdbc.Driver"
and user="ADMIN"
and password="KYLIN"
and ispushdown="true"
as db_2;

load jdbc.`db_2.KYLIN_SALES` as kylin_sales_t;

select t1.BUYER_ID, t1.ss, t2.ss as s2 from 
(select BUYER_ID,sum(price) as ss from kylin_sales_t where OPS_REGION="Shanghai" group by BUYER_ID) t1 
join 
(select BUYER_ID,sum(price) as ss from kylin_sales_my1 group by BUYER_ID) t2 
on t1.BUYER_ID=t2.BUYER_ID 
as output;

-------------------目前有问题 ----------------------------

connect jdbc where
url="jdbc:kylin://localhost:7070/learn_kylin"
and driver="org.apache.kylin.jdbc.Driver"
and user="ADMIN"
and password="KYLIN"
and ispushdown="true"
as db_2;

load jdbc.`db_2.KYLIN_SALES` as kylin_sales;

--- 目前的聚合查询需要有别名
select sum(price),count(1),BUYER_ID from kylin_sales where BUYER_ID=10001779  group by BUYER_ID as output;

```

2021-04-12 07:45 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdownable.scala
> +  val supportedOperators: Seq[Class[_]]
Seq 可以转换成 Set之类的，我看后续会有大量的包含判断操作。

2021-04-12 07:45 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdownable.scala
> +  val supportedOperators: Seq[Class[_]]
其他几个也是如此

2021-04-12 07:59 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdownSourceInfo.scala
> +    val newlp = newlp2.transformDown{
能解释下这段代码的含义么？

2021-04-12 08:03 UTC, allwefantasy commented
我觉得这个PR可以分成两个阶段。第一个阶段是当前这个PR。
第二阶段，我们新起一个PR，主要是可解释性。改写时，应该要收集一些信息，比如为什么能改写（如果不能改写，是什么导致不能改写），改写的部分是哪些，改写时间消耗等，让用户可以很清晰的看到下推的信息，第一步可以以日志的方式打印出来。

2021-04-12 08:27 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdownSourceInfo.scala
> +    val newlp = newlp2.transformDown{
这个段因为 上面生成的 newlp2 导致需要改写一些东西。因为在 加载数据源时 有个 load source_table_name  as mlsql_tablename，那么在生成查询是 最底层就会包含 select * from source_table_name as mlsql_tablename. 但是在下压时生成的sql应该直接从table_source_name 这个原始表进行查询 ，那么就需要去除外层的 subquerys 和 project，这个修改之后，外层的表名就得发生变化 从mlsql_tablename 改为 table_source_name。这段代码就是为了 把外层的表改成 原始表

2021-04-12 08:28 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdownSourceInfo.scala
> +    val newlp = newlp2.transformDown{
上面的处理方式是是直接把外层中mlsql_tablename 直接去掉了

2021-04-12 08:30 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdownable.scala
> +  val supportedOperators: Seq[Class[_]]
好的,我处理一下

2021-04-12 09:17 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/KylinPushdownSourceInfo.scala
> +    val newlp = newlp2.transformDown{
明白了。我觉得PR没啥问题了。那我直接合并了。

2021-04-12 09:20 UTC, merged