add mlsql script execute
byzer-org/byzer-lang pull request #1416
Opened 2021-04-01 09:25 UTC by fanfanAlice

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-04-01 09:49 UTC, allwefantasy requested changes

2021-04-01 09:49 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/job/RunScriptExecutor.scala
> +  def execute(sparkSession: SparkSession): (Int, String) = {
这里并不需要传入sparkSession对象，因为你可以通过getSession/getSessionByOwner 获取。

2021-04-01 09:49 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/job/RunScriptExecutor.scala
> +  def execute(sparkSession: SparkSession): (Int, String) = {
另外，有什么理由不适用前面已经实现的execute方法？

2021-04-01 09:49 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/runtime/SparkSubmitMLSQLScriptRuntimeLifecycle.scala
> +    val array = rootSparkSession.sparkContext.textFile(mlsql_path).collect()
这里可以留个口子，比如支持local disk/hdfs/http 等。 可以稍微设计下。

2021-04-01 09:49 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/runtime/SparkSubmitMLSQLScriptRuntimeLifecycle.scala
> +    executor.execute(rootSparkSession)
JobManager的 init 和 shutdown可以在executor之前和之后做，而不是嵌入到RunScriptExecutorLi做。另外应该允许用户传递owner，如果不传应该就用RootSession.

2021-04-01 09:50 UTC, allwefantasy commented
另外，可以加上使用说明。

2021-04-01 10:48 UTC, fanfanAlice commented on streamingpro-core/src/main/java/tech/mlsql/job/RunScriptExecutor.scala
> +  def execute(sparkSession: SparkSession): (Int, String) = {
在引用原来的 execute() 方法中 val sparkSession = getSession ,  getSession 方法中用引用了 runtime , runtime 又是引用的
PlatformManager.getRuntime 一路往下 一直调用 getOrCreate 方法，陷入循环状态

2021-04-05 12:28 UTC, allwefantasy requested changes

2021-04-05 12:28 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/runtime/SparkSubmitMLSQLScriptRuntimeLifecycle.scala
>      val executor = new RunScriptExecutor(params ++ Map("sql" -> sql.toString, "owner" -> "admin", "jobName" -> "SparkSubmitMLSQLScriptRuntimeLifecycle"))
可以多加一个参数，比如streaming.mlsql.script.owner= 来传递用户，而不是写死admin。如果用户没有配置，那么就不传递owner.

2021-04-05 14:57 UTC, zzcclp commented
基于 @fanfanAlice 的这个PR，在 #1419  修复了调用RunScriptExecutor.execute()的问题，麻烦两位Review下。

2021-04-06 02:22 UTC, merged