Optimize Pushdown Index
byzer-org/byzer-lang pull request #1420
Opened 2021-04-13 12:28 UTC by liuyonghengheng

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-04-13 12:32 UTC, liuyonghengheng commented
这个pr 是开启 聚合下推 第二阶段的工作，目前增加了一些日志，输出每个查询优化占用时间，优化前和优化后的子树，以及优化前后的整个逻辑计划树

2021-04-14 03:08 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/MysqlPushdownSourceInfo.scala
> +    // mlsql 生成的jdbc数据源的逻辑计划都会有这个子树
棒，有针对性的优化

2021-04-14 03:10 UTC, allwefantasy requested changes

2021-04-14 03:10 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdown.scala
> +          logError("----Old sub Logicplan:" + lp.toString())
能不能通过参数来控制日志输出？比如在脚本里写入 set RewriteDebugMode="true"; 你获得这个信息，然后再打印logInfo.

2021-04-14 03:10 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdown.scala
> +          logError("----Old sub Logicplan:" + lp.toString())
或者也可以通过其他方式动态控制日志的打印比较稳妥。

2021-04-14 06:33 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdown.scala
> +          logError("----Old sub Logicplan:" + lp.toString())
好的，我这边再完善一下

2021-04-16 02:14 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdown.scala
> +          logError("----Old sub Logicplan:" + lp.toString())
貌似还没有看到通过参数控制日志输出的？ 因为几乎所有的查询都会尝试改写，如果不加参数控制，就会导致大量的日志打印。

可以参看我的一个修改：

```scala
val params = JSONTool.parseJson[Map[String, String]](ScriptSQLExec.context().userDefinedParam.getOrElse("__PARAMS__", "{}"))
    val setParams = ScriptSQLExec.context().execListener.env()

    if (!params.getOrElse("enableQueryWithIndexer", "false").toBoolean &&
      !setParams.getOrElse("enableQueryWithIndexer", "false").toBoolean) {
      return d
    }
```

第一个参数是Console控制的，也就是HTTP参数，第二个是用户在脚本里通过

```
set enableQueryWithIndexer = "true";
```
的方式进行设置。只要有一个为true,我们都会尝试进行改写。同理，日志输出也是可以这样的。

2021-04-20 11:53 UTC, liuyonghengheng commented
添加参数控制优化日志输出：
参数: enableAggPushdownLog
类型: Boolean
默认值: false
使用方式：
```sql
connect jdbc where
url="jdbc:mysql://localhost:3306/learn_kylin?characterEncoding=utf8"
and driver="com.mysql.jdbc.Driver"
and user="root"
and password="yourpasswd"
and ispushdown="true"
as db_1;

load jdbc.`db_1.kylin_sales_my1` as kylin_sales_my1;
load jdbc.`db_1.kylin_sales_my2` as kylin_sales_my2;

set enableQueryWithIndexer="true";
set enableAggPushdownLog="true";
select t1.BUYER_ID, t1.ss, t2.ss as s2 from 
(select BUYER_ID,sum(price) as ss from kylin_sales_my1 where OPS_REGION="Shanghai" group by BUYER_ID) t1 
join 
(select BUYER_ID,sum(price) as ss from kylin_sales_my2 group by BUYER_ID) t2 
on t1.BUYER_ID=t2.BUYER_ID 
as output;
```

2021-04-20 13:17 UTC, allwefantasy commented
另外，我觉得这个可以比较好的加单元测试。可以加一个单元测试试试。

2021-04-20 13:47 UTC, merged

2021-04-20 13:47 UTC, allwefantasy approved these changes

2021-04-20 13:47 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/Pushdown.scala
> +    val rootStartTime = System.currentTimeMillis()
比如 criptSQLExec.context().execListener.env()  可以独立出一个scriptParams方法,ScriptSQLExec.context().userDefinedParam.getOrElse("__PARAMS__", "{}")) 独立成httpParams方法

获取参数就可以 scriptParams..getOrElse("enableAggPushdownLog", "false").toBoolean 这样了

然后获取这个参数的逻辑也可以独立包装成方法