add pushdown UT
byzer-org/byzer-lang pull request #1429
Opened 2021-04-29 05:00 UTC by liuyonghengheng

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-04-29 05:06 UTC, liuyonghengheng commented
聚合下压功能的单元测试，为了测试方便，添加了H2数据库，通过H2数据库进行功能验证。但是目前还没有mysql和kylin的验证，因为这个需要使用Docker 或者现有mysql和kylin系统进行测试，不太方便放在UT中进行。后续可以添加集成测试。

2021-04-30 01:34 UTC, allwefantasy requested changes
其他部分我觉得都很好；可以修改下我提及的；

2021-04-30 01:34 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/H2PushdownSourceInfo.scala
> +case class H2PushdownSourceInfo(props: Map[String, String], sparkSession: SparkSession, lr:LogicalRelation) extends PushdownSourceInfo(props) with Pushdownable {
不同的PushdownSourceInfo都有大量相同的实现；能否抽出一个base class 亦或是提供一个工具类，将相同实现的部分抽取出来？否则导致目前的三个实现类大量重复代码；

2021-04-30 01:34 UTC, allwefantasy commented on external/mlsql-sql-profiler/src/test/java/org/apache/spark/sql/optimizer/PushDownSuite.scala
> +    conn.close()
Close就可以么？需不需要清理文件啥的？

2021-04-30 04:16 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/main/java/org/apache/spark/sql/optimizer/H2PushdownSourceInfo.scala
> +case class H2PushdownSourceInfo(props: Map[String, String], sparkSession: SparkSession, lr:LogicalRelation) extends PushdownSourceInfo(props) with Pushdownable {
不同的 PushdownSourceInfo 基本上都继承了 Pushdownable 这个抽象类，基本上也都是实现的Pushdownable里面的方法，重复的也都是这一块的代码，虽然重复度高但是不同的实现还是有些差别，好像不太好共用。PushdownSourceInfo这个抽象类只是记录一些具体的表的关于下压的信息。

2021-04-30 04:16 UTC, liuyonghengheng commented on external/mlsql-sql-profiler/src/test/java/org/apache/spark/sql/optimizer/PushDownSuite.scala
> +    conn.close()
直接close就行不用手动清理数据。这个是用内存模式，直接关闭数据库，数据就没有了。

2021-05-05 00:45 UTC, merged