Issue 1486 Support json expand as table
byzer-org/byzer-lang pull request #1507
Opened 2021-08-19 14:05 UTC by chncaesar

# What changes were proposed in this pull request?
Plugin Class:  JsonExpandExt

# How was this patch tested?
Passed ut and it.
Unit test: JsonExpandExtSuite
Integration test:  09_run_json_expand_ext.mlsql 09_run_json_expand_ext.mlsql.expected

# Are there and DOC need to update?
Document will be a separate PR 

# Spark Core Compatibility
Compatible with Spark 3 & 2.4

2021-08-20 07:30 UTC, allwefantasy requested changes

2021-08-20 07:30 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +object JsonExpandExt {
You should put all your param declaration in class instead of object .

2021-08-20 07:30 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +//    ScriptSQLExec.contextGetOrForTest.execListener.sparkSession
Please implement this auth function.

2021-08-20 07:30 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +        val expandedCol = from_json( df( col ), schema).as("expanded")
we should keep other columns which are not from json

2021-08-20 07:30 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +      |SELECT '{"key": "value", "key_2":"value_2"}' AS col_1 AS table_1;
SELECT '{"key": "value", "key_2":"value_2"}' AS col_1 , "" as col_2 AS table_1;
run table_1 as JsonExpandExt.`` where inputCol="col_1" AND samplingRatio = "0.5" as A2;

A2 should contains three columns: key,key_2,col_2

2021-08-20 07:30 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +class JsonExpandExt (override val uid: String) extends SQLAlg with WowParams with Logging with WowLog with ETAuth {
Please overwrite functions e.g. `modelType`. More details please check `streaming.dsl.mmlib.SQLAlg`

2021-08-20 07:35 UTC, allwefantasy requested changes

2021-08-20 07:35 UTC, allwefantasy commented on external/mlsql-ets/src/test/scala/tech/mlsql/plugins/ets/JsonExpandExtSuite.scala
> +package tech.mlsql.plugins.ets
This test is no need.  Use integrated test in streamingpro-it .

2021-08-20 07:35 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/09_run_json_expand_ext.mlsql
> +SELECT '{"key": "value", "key_2":"value_2"}' AS col_1 AS table_1;
Please use !assert  instead expected.

2021-08-20 07:35 UTC, allwefantasy commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
> +    // Load built-in and external plug-ins and start PlatformManager
This is a bug in streamingpro-it ？ If so ,please issue a new PR instead in this PR .

2021-08-20 07:35 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/tech/mlsql/example/app/LoalSparkServiceApp.scala
> +      "-streaming.workAs.schedulerService.consoleUrl", "http://127.0.0.1:19002",
This file should not modify. You can create your own LocalSparkServiceApp e.g. WilliamLocalSparkServiceApp then add it in .gitignore.

2021-08-20 07:35 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/tech/mlsql/example/app/LoalSparkServiceApp.scala
> +      "-streaming.driver.port", "19003"
LocalSparkServiceApp should not modify.

2021-08-26 02:14 UTC, allwefantasy requested changes

2021-08-26 02:14 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +        val query = s"""SELECT ${(otherCols ++ expandedCols ).mkString(",")} FROM sourceDF""".stripMargin
Please use DataFrame api instead of SQL

2021-08-26 02:16 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +object JsonExpandExt {
done, see latest code

2021-08-26 02:16 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +        val expandedCol = from_json( df( col ), schema).as("expanded")
done, see latest code

2021-08-26 02:17 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +class JsonExpandExt (override val uid: String) extends SQLAlg with WowParams with Logging with WowLog with ETAuth {
done, see latest code

2021-08-26 02:17 UTC, chncaesar commented on streamingpro-it/src/test/resources/sql/simple/09_run_json_expand_ext.mlsql
> +SELECT '{"key": "value", "key_2":"value_2"}' AS col_1 AS table_1;
done, see latest code

2021-08-26 02:17 UTC, chncaesar commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
> +    // Load built-in and external plug-ins and start PlatformManager
mlsql pr 1511

2021-08-26 02:18 UTC, chncaesar commented on streamingpro-mlsql/src/main/java/tech/mlsql/example/app/LoalSparkServiceApp.scala
> +      "-streaming.driver.port", "19003"
Code has been reverted.

2021-08-26 02:18 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +        val query = s"""SELECT ${(otherCols ++ expandedCols ).mkString(",")} FROM sourceDF""".stripMargin
ok.

2021-08-26 02:52 UTC, allwefantasy requested changes

2021-08-26 02:52 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainParams(sparkSession: SparkSession): DataFrame = {
1) This explainParams impl is not right.  We should output all param message instead of just name.
2)  No need to overwrite explainParams since it's parent impl works already.

2021-08-26 02:52 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainModel(sparkSession: SparkSession, path: String, params: Map[String, String]): DataFrame = {
This method is only required  when you develop algorithm ET.

2021-08-26 03:02 UTC, lwz9103 commented on external/mlsql-ets/pom.xml
> +
please remove useless changes

2021-08-26 03:02 UTC, lwz9103 commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
>  import org.scalatest.{BeforeAndAfterAll, FunSuite}
please remove useless changes

2021-08-26 03:06 UTC, lwz9103 commented
When using github, please write commit start with `#issue_id` so that github can make internal associations.

2021-08-26 03:08 UTC, chncaesar commented on external/mlsql-ets/src/test/scala/tech/mlsql/plugins/ets/JsonExpandExtSuite.scala
> +package tech.mlsql.plugins.ets
Removed.

2021-08-26 03:09 UTC, chncaesar commented on streamingpro-mlsql/src/main/java/tech/mlsql/example/app/LoalSparkServiceApp.scala
> +      "-streaming.workAs.schedulerService.consoleUrl", "http://127.0.0.1:19002",
Code is reverted

2021-08-26 03:11 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainParams(sparkSession: SparkSession): DataFrame = {
Got it. thanks.

2021-08-26 03:12 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainModel(sparkSession: SparkSession, path: String, params: Map[String, String]): DataFrame = {
OK, will remove this method

2021-08-26 03:13 UTC, chncaesar commented on external/mlsql-ets/pom.xml
> +
will do

2021-08-26 03:13 UTC, chncaesar commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
>  import org.scalatest.{BeforeAndAfterAll, FunSuite}
will do

2021-08-26 05:47 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +        val query = s"""SELECT ${(otherCols ++ expandedCols ).mkString(",")} FROM sourceDF""".stripMargin
Done. Use DataFrame API.

2021-08-26 05:48 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainParams(sparkSession: SparkSession): DataFrame = {
By parent impl, it means WowParams. Fixed.

2021-08-26 05:48 UTC, chncaesar commented on external/mlsql-ets/pom.xml
> +
fixed

2021-08-26 05:49 UTC, chncaesar commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
>  import org.scalatest.{BeforeAndAfterAll, FunSuite}
fixed

2021-08-26 05:49 UTC, chncaesar commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/JsonExpandExt.scala
> +    override def explainModel(sparkSession: SparkSession, path: String, params: Map[String, String]): DataFrame = {
done

2021-08-26 06:55 UTC, lwz9103 approved these changes

2021-08-26 06:56 UTC, allwefantasy approved these changes

2021-08-26 06:57 UTC, merged