Add integration test of SyntaxAnalyzeExt ET
byzer-org/byzer-lang pull request #1508
Opened 2021-08-19 14:46 UTC by hellozepp

1. Fix default value of SyntaxAnalyzeExt parameter
2. Add integration test of SyntaxAnalyzeExt ET

2021-08-20 08:55 UTC, allwefantasy requested changes

2021-08-20 08:55 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/09_syntax_analysis_ext_test.mlsql
> +select 1 as a as b;
Please use !assert instead of `expected`

2021-08-20 08:55 UTC, allwefantasy commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
> +    // Load built-in and external plug-ins and start PlatformManager
Remove this since PR https://github.com/allwefantasy/mlsql/pull/1511  have resolved this issue already.

2021-08-23 03:18 UTC, allwefantasy requested changes

2021-08-23 03:18 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/SyntaxAnalyzeExt.scala
> +      | select "stub" as table1;
This two lines :

1. Have wrong syntax.
2. No need stub table to make your ET works.

2021-08-23 03:18 UTC, allwefantasy commented on external/mlsql-ets/src/main/java/tech/mlsql/plugins/ets/SyntaxAnalyzeExt.scala
> +      | Required. SQL to be analyzed
Also you should issue a new PR to fix the doc in https://github.com/allwefantasy/mlsql-docs/commit/204a8ad1daf730991ccf99169831f52a34379547

2021-08-23 09:48 UTC, allwefantasy approved these changes

2021-08-23 09:50 UTC, lwz9103 approved these changes

2021-08-23 09:51 UTC, merged