support grid search for linear and logistic regression learning
byzer-org/byzer-lang pull request #1509
Opened 2021-08-20 08:16 UTC by ckeys

# What changes were proposed in this pull request?
We support grid search for linear regression and logistic regression models by group params.

In addition, I change the mapping name from 'LinearRegressionExt' to 'LinearRegression' and 'LogisticRegressor' to 'LogisticRegression'

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-08-20 08:19 UTC, allwefantasy commented
Please use following commands to combine three commits to one commits:

```shell
git rebase -i HEAD~3
```

then force push :

```shell
git push --force ckeys pengyi_master
```

2021-08-20 08:23 UTC, allwefantasy commented
1. integrated test is missing
2. Please overwrite functions:  doc/modelType/codeExample/explainModel/auth

2021-08-23 03:41 UTC, allwefantasy requested changes

2021-08-23 03:41 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/andie_huang_01_train_logistic_regression_model.mlsql
> +--%exception=java.lang.RuntimeException
The first two lines should be deleted.

2021-08-23 03:41 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/andie_huang_02_train_linear_regression_model.mlsql
> +--%exception=java.lang.RuntimeException
Like the first test. Please delete the first two lines.

2021-08-23 03:41 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/andie_huang_02_train_linear_regression_model.mlsql
> +!plugin app remove "mlsql-assert-2.4";
This two lines is required?

2021-08-23 08:00 UTC, allwefantasy requested changes

2021-08-23 08:00 UTC, allwefantasy commented on streamingpro-it/src/test/scala/tech/mlsql/it/LocalBaseTestSuite.scala
> +    StreamingApp.main(runParams)
You should pull latest  code first

2021-08-23 08:05 UTC, allwefantasy commented
Please issue new docs about this two algorithms in https://github.com/allwefantasy/mlsql-docs

2021-08-23 09:50 UTC, allwefantasy approved these changes

2021-08-23 10:48 UTC, lwz9103 approved these changes

2021-08-23 10:48 UTC, merged