Modify DriverLogServer to HTTP
byzer-org/byzer-lang pull request #1520
Opened 2021-08-25 09:10 UTC by hellozepp

# background
MLSQL Engine is a typical distributed system with a master-slave structure. Because it is multi-tenant and programmable (such as printing with Print in python), these need to be displayed on the web page, and only the logs related to this user are echoed. And now the log system has the following problems:
1. Using Socket connection will cause too many socket connections on the driver side.
2. At present, the log received by the driver is written into the log file, and then the log file will be read through the driver to filter out the logs required by the user.

# Expected goal
1. MLSQL log collection is transformed to HTTP
2. Plug-in log collection, allowing different implementations to be configured.

# Technical solutions
## 1. MLSQL log interface transformation
### 1.1 HTTPClient fluent API pre-research (on the scala side)
View the flow of auth module using fluent API

### 1.2 Python uses its own request library

### 1.3 socket replaced with HTTP
 > Use http fluent api as a short connection to receive executor logs
1) Transform DriverLogServer into HTTPServer
2) The DriverLogServer in SparkRuntime.scala is modified to be obtained by reflection, and set to option to support configuration.
Previously, the fixed option in `SparkRuntime.scala`:
```
spark.mlsql.log.driver.host
spark.mlsql.log.driver.port
spark.mlsql.log.driver.token
```

Option to be transformed:
```
-spark.mlsql.log.driver.server.url # Newly implement a DriverLogServer, get the driver's local host:port/api_v1/writelog by default, and the port can be generated by yourself

-spark.mlsql.log.driver.access_token #The request header parameter accessToken is UUID; Worker will get it from spark conf and compare whether the access_token carried in the request is legal
```

Refer to several options used by Auth:
```
1. Startup configuration items:
-spark.mlsql.auth.implClass: streaming.dsl.auth.client.DefaultConsoleClient

2. userDefinedParam:
__auth_server_url__: Configured for the Engine settings configuration page of the Console, the field is consoleUrl
__auth_secret__: Configured for the Engine settings configuration page of the Console, the field is accessToken

3. Settings configuration items in `application.yml`:
auth_secret: "mlsql"
```

3) WriteLog in `RedirectStreamsToSocketServer.scala` is a socket thread, and the log consumption thread here needs to be changed to HTTP.

4) HTTP transformation on Python side
The python side is divided into two log output methods, one is processed by the scala code in the Executor through the standard output stream and the exception stream, and the other is through the LogClient.
-The first type does not require modification, and the modification point is on the scala side
-The second, you need to change the LogClient in the mlsql.py script to HTTP (you need to confirm whether there is a difference between the daemon and worker methods)

2021-08-26 02:54 UTC, allwefantasy commented on streamingpro-core/src/main/java/streaming/core/strategy/platform/SparkRuntime.scala
> +  var driverLogServer: HttpServerInExecutor[String] = null
HttpLogServer in Driver instead of in  Executor

2021-08-30 08:33 UTC, allwefantasy requested changes

2021-08-30 08:33 UTC, allwefantasy commented on streamingpro-core/src/main/java/streaming/core/strategy/platform/SparkRuntime.scala
> +        params.getOrElse("spark.mlsql.log.driver.server.url", "tech.mlsql.log.DriverLogServer").toString)
So ,is  spark.mlsql.log.driver.server.url  a class name? I guess it's just http url.

2021-08-30 08:33 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/log/DriverLogServer.scala
> +class DriverLogServer[T](taskContextRef: AtomicReference[T]) extends HttpServerInExecutor[T](taskContextRef, "driver-log-server-in-driver") with Logging {
Do not copy concept from old impl. Please write new impl.

2021-08-30 08:37 UTC, allwefantasy requested changes

2021-08-30 08:37 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/log/BaseHttpLogClient.scala
> +  def readRequest(dIn: DataInputStream, length: Int): Any = {
Should we remove this function?

2021-08-30 08:37 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/log/BaseHttpLogClient.scala
> +  def readRequest(dIn: DataInputStream): Any = {
Also this

2021-09-01 06:52 UTC, hellozepp commented
## Test case
Case 1: Verify whether `print` and `log_client.log_to_driver` in the python code are sent to DriverLogServer via WriteLog, and whether the log is displayed on the Console side.

Case 2: Explicitly configure implClass, url, ip, port, and token in the configuration parameters of starting the Engine to see whether the above 5 parameters are effective as configured and whether the Server can be started normally.

Case 3: After verifying that the abnormal message reception caused DriverLogServer to report an error and discard the message when handling, the error log can be seen in the Console, and whether the DriverLogServer can still receive messages normally.

Case 4: DriverLogServer refuses to receive messages with illegal tokens.

Case 5: Verify whether UTF-8 encoded Chinese characters are received normally.

Case 6: In the case of verifying the user-defined port, restart the service after the server is closed, and whether the port can be reused.

## Regression use case
Case 7: Verify the standardized format of the log. Whether the log in the non-standardized format can be filtered out normally will not be echoed to the Console.

Case 8: The HTTP transformation of DriverLogServer will not affect the normal Socket communication between dataServer and modelServer, the Server can be started normally, and the model results can be normally echoed.

## Verification steps and results

> Case 1: Verify whether the print and log_client.log_to_driver in the python code are sent to DriverLogServer via WriteLog, and whether the log is displayed on the Console side.
Execute the following SQL:
```
!python env "PYTHON_ENV=source activate base";
!python conf "schema=st(field(petalLength,double),field(petalWidth,double),field(sepalLength,double),field(sepalWidth,double),field(species,string))";
!python conf "dataMode=model";

!ray on command'''
import time

for i in range(5):
    print("---log_client msg1--")
    context.log_client.log_to_driver("---log_client msg2--")
''' named mlsql_temp_table;

select * from mlsql_temp_table as output;
```

The log is as follows:
![image](https://user-images.githubusercontent.com/20615623/131625130-2f3b5fb2-ffd0-48fc-9870-b2fe49c5aaa1.png)




> Case 2: Explicitly configure implClass, url, ip, port, and token in the configuration parameters of starting the Engine to see if the above 5 parameters are effective as configured, and whether the Server can be started normally.
The configuration of the startup class is as follows:
```
"-spark.mlsql.log.driver.implClass", "tech.mlsql.log.MyDriverLogServer",
"-spark.mlsql.log.driver.url", "http://192.168.1.100:12345/v2/writelog_1",
"-spark.mlsql.log.driver.host", "192.168.1.100",
"-spark.mlsql.log.driver.port", "12345",
"-spark.mlsql.log.driver.token", "zhanglin",
```

Check whether it takes effect:
![image](https://user-images.githubusercontent.com/20615623/131625192-f4cb117e-fd42-4fb5-8197-4d93c6098cf5.png)




> Case 3 & Case 4: Verify that the abnormal message reception caused DriverLogServer to report an error and discard the message during the handle. Check whether the error log is normally seen in the Console and whether the DriverLogServer can still receive messages normally. Verify that DriverLogServer refuses to receive messages with illegal tokens.
Send an illegal message through python:
```
# -*- coding:utf-8 -*-
import json
import requests

url ='http://127.0.0.1:12345/v2/writelog_1'

headers = {'content-type':'application/x-www-form-urlencoded;charset=UTF-8'}
requests = requests.post(url, data="xxx", headers=headers)
print(requests.content)
```

Then, send an illegal token message through python:
```
# -*- coding:utf-8 -*-
import json
import requests

url ='http://192.168.1.100:12345/v2/writelog_1'
data = json.dumps(
    {"sendLog": {"token": "78fd4d1a-796a-48d3-bcb2-a5ec5f0fc00e", "logLine": "xxx"}}, ensure_ascii=False)

headers = {'content-type':'application/x-www-form-urlencoded;charset=UTF-8'}
requests = requests.post(url, data=data, headers=headers)
print(requests.content)
```

The server caught the following Exceptions, 1st is an exception stack, error 2nd is an illegal token, and finally the normal request processing:
![image](https://user-images.githubusercontent.com/20615623/131625312-f2a15c41-9fa9-4e8a-854f-eebf05bb04e3.png)
![image](https://user-images.githubusercontent.com/20615623/131625337-30962558-6eb4-47f3-996e-ad6894e03878.png)





> Case 5: Verify whether UTF-8 encoded Chinese characters are received normally.
Set the output of Chinese in SQL:
```
!python env "PYTHON_ENV=source activate it_env";
!python conf "schema=st(field(petalLength,double),field(petalWidth,double),field(sepalLength,double),field(sepalWidth,double),field(species,string))";
!python conf "dataMode=model";

!ray on command'''
import time

for i in range(5):
    print("---Chinese--")
    context.log_client.log_to_driver("---Chinese--")
''' named mlsql_temp_table;

select * from mlsql_temp_table as output;
```

The log is as follows:
![image](https://user-images.githubusercontent.com/20615623/131625384-be80b749-a85f-42e6-b9bd-3ba9491ac24d.png)




> Case 6: In the case of verifying the user-defined port, restart the service after the server is closed, and whether the port can be reused.
After restarting the service, it successfully started on the port:
![image](https://user-images.githubusercontent.com/20615623/131625412-8cb7183c-cadc-4def-8606-073696b837db.png)




> Case 7: Verify the standardized format of the log. Whether the log in the non-standardized format can be filtered out normally, it will not be echoed to the Console.
Use python to send logs as follows:
```
# -*- coding:utf-8 -*-
import json
import requests

url ='http://192.168.1.100:12345/v2/writelog_1'
data = json.dumps(
    {"sendLog": {"token": "zhanglin", "logLine": "xxx"}}, ensure_ascii=False)

headers = {'content-type':'application/x-www-form-urlencoded;charset=UTF-8'}
requests = requests.post(url, data=data, headers=headers)
print(requests.content)
```

The log can be received normally, but because it is not in the standard MLSQL log format, it will not be displayed in the Console:
![image](https://user-images.githubusercontent.com/20615623/131625457-df8529b9-31d6-4935-b665-91f58df92f67.png)



> Case 8: The HTTP transformation of DriverLogServer will not affect the normal Socket communication between dataServer and modelServer, the Server can be started normally, and the model results can be normally echoed.
The SQL is as follows:
```
!python env "PYTHON_ENV=source activate base";
!python conf "schema=st(field(petalLength,double),field(petalWidth,double),field(sepalLength,double),field(sepalWidth,double),field(species,string))";
!python conf "dataMode=model";

!ray on command'''
from vega_datasets import data
import time

for i in range(10):
    time.sleep(2)
    print(12345)


df = data.iris()

context.log_client.log_to_driver("---log_client msg--")
context.set_output([[df[name] for name in df]])


''' named mlsql_temp_table2;

select * from mlsql_temp_table2 as output;
```

The socketServer startup log is as follows:
![image](https://user-images.githubusercontent.com/20615623/131625483-6834a6d0-8a0a-4010-a4af-da813146fa6c.png)

The model results are as follows:
![image](https://user-images.githubusercontent.com/20615623/131625498-df3ed329-7e9a-47a0-af7a-108491064a50.png)

2021-09-01 07:07 UTC, lwz9103 approved these changes

2021-09-01 07:07 UTC, lwz9103 commented on streamingpro-core/src/main/java/tech/mlsql/log/RedirectStreamsToSocketServer.scala
> -class WriteLogPool(size: Int, conf: Map[String, String]) {
It's better to keep the original implementation and specify the new implementation through default config.

2021-09-01 07:09 UTC, allwefantasy approved these changes

2021-09-01 07:17 UTC, merged