Use urlendcode format log
byzer-org/byzer-lang pull request #1535
Opened 2021-09-07 10:01 UTC by hellozepp

# Problem Description:
When I tested in the morning, I found that the "=" or "&" in the request data would cause the log display to be incomplete. It was located because the encoding method of sending data in fluemt is: Content-Type=application/x-www-form-urlencoded format, This format requires the data to be encoded in the way of key1=val1&key2=val2. If there is a "=" separator, it will be split into multiple sets of parameters, and I only took the first set of json text data in jetty.

# solution:
Urlencode the log with special characters

2021-09-07 10:14 UTC, hellozepp commented
Test case:
Execute the following SQL, call log_client in print and pyjava respectively:
```
!python env "PYTHON_ENV=source activate root";
!python conf "schema=st(field(petalLength,double),field(petalWidth,double),field(sepalLength,double),field(sepalWidth,double),field(species,string))";
!python conf "dataMode=model";

!ray on command '''
import time

for i in range(5):
    print("a=1&b=2---log_client msg1--")
    context.log_client.log_to_driver("a=1&b=2---log_client msg2--")
''' named mlsql_temp_table;

select * from mlsql_temp_table as output;
```

The results are as follows:
![image](https://user-images.githubusercontent.com/20615623/132328013-fc286240-7642-48b1-9829-f0c326091565.png)

2021-09-08 02:25 UTC, allwefantasy requested changes

2021-09-08 02:25 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/log/BaseHttpLogClient.scala
> +        Request.Post(url).addHeader("Content-Type", "application/x-www-form-urlencoded")
Since you use json body,  you can use application/json mime.

2021-09-08 02:27 UTC, allwefantasy requested changes

2021-09-08 02:27 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/log/BaseHttpLogClient.scala
> +          .bodyForm(Form.form().add(body, null).build()).execute()
It's not ok using  `add(body,null)` . Form params should be key-value format.

2021-09-08 03:03 UTC, hellozepp commented
Test case:
Execute the following SQL, call log_client in print and pyjava respectively:
```
!python env "PYTHON_ENV=source activate root";
!python conf "schema=st(field(petalLength,double),field(petalWidth,double),field(sepalLength,double),field(sepalWidth,double),field(species,string))";
!python conf "dataMode=model";

!ray on command '''
import time

for i in range(5):
    print("a=1&b=2---log_client msg1--")
    context.log_client.log_to_driver("a=1&b=2---log_client msg2--")
''' named mlsql_temp_table;

select * from mlsql_temp_table as output;
```

The results are as follows:
![image](https://user-images.githubusercontent.com/20615623/132439620-32acfd74-1f02-481a-8ed6-ddb9bc7821f7.png)

2021-09-13 02:18 UTC, allwefantasy approved these changes

2021-09-13 04:01 UTC, hellozepp commented
merge code of master

2021-09-13 05:19 UTC, chncaesar approved these changes

2021-09-13 05:20 UTC, merged