#1544 support define plugin compatibility version by range
byzer-org/byzer-lang pull request #1548
Opened 2021-09-14 13:55 UTC by lwz9103

# What changes were proposed in this pull request?
- [x] Finshed changes describe
  see #1544

# How was this patch tested?
- [x] Testing done

# Are there and DOC need to update?
- [x] Doc is finished

# Spark Core Compatibility

2021-09-14 21:05 UTC, allwefantasy requested changes
Can you provide some unit tests for VersionRangeChecker

2021-09-14 21:09 UTC, allwefantasy commented
Notice that we hope we can also check the spark core version, e.g the plug-in developer can define version like this ">=2.1.0/=2.4.3". The first part is mlsql engine version and the second part is spark core version

2021-09-14 21:50 UTC, allwefantasy commented
MLSQL will also check version compatibility in class TrainAdaptor, so in this PR we need to change that too.

2021-09-15 12:12 UTC, allwefantasy approved these changes

2021-09-15 13:02 UTC, chncaesar approved these changes

2021-09-15 13:02 UTC, merged