revise the code example
byzer-org/byzer-lang pull request #1640
Opened 2021-12-27 03:04 UTC by ckeys

# What changes were proposed in this pull request?
- [ ] Revise the code example in the script. 

# How was this patch tested?
- [ ] Testing is done in the it file

# Spark Core Compatibility

2021-12-29 05:47 UTC, allwefantasy commented
1. The function trainByGroup is not used so it  should be removed.
2. There are no predict example(register model as UDF and then run the test on example data)

2021-12-29 05:50 UTC, allwefantasy requested changes

2021-12-29 05:50 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLDiscretizer.scala
> +  def isGroupParams(params: Map[String, String]): Boolean = {
It's better to rename to something like `checkWithoutGroupParams` and put the require/assert in this function.
So we can use this function to make sure there no groupParam prefix in params.

2021-12-30 13:07 UTC, hellozepp commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLDiscretizer.scala
>      """.stripMargin)
Good job! Should we leave some explanation in codeExample, such as the meaning of `splits`.

In addition, I have not seen an example of how to register and how to use it. Can you add it?

2022-01-04 03:30 UTC, hellozepp approved these changes

2022-01-04 03:33 UTC, hellozepp approved these changes

2022-01-04 05:22 UTC, chncaesar approved these changes

2022-01-11 09:32 UTC, allwefantasy approved these changes

2022-01-11 09:32 UTC, merged