Variables are nested variables#issues-1645
byzer-org/byzer-lang pull request #1648
Opened 2021-12-30 08:45 UTC by anan0120

# What changes were proposed in this pull request?
[- [ ] Finshed changes describe](https://github.com/byzer-org/byzer-lang/issues/1645)

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2021-12-30 09:00 UTC, allwefantasy requested changes

2021-12-30 09:00 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/20_nesting_variables_across_cells_test.mlsql
> +!assert result ''':name=="ODS_T_TableName"'''  "all model status should be success";
This line equals:

assert(:name=="ODS_T_Table_Name", "The variable ods_table_name should be ODS_T_TableName")

So it's better to change the description in the last part.

2021-12-30 09:07 UTC, anan0120 commented
Corrected

2021-12-30 10:47 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/20_nesting_variables_across_cells_test.mlsql
> +!assert result ''':name=="ODS_T_TableName"'''  "all model status should be success";
1) remove the comment line `--make sure satus....`;
2) change the description `all model status should be success` which is not suite for your test.

2021-12-30 13:47 UTC, anan0120 commented
update nesting_variables_across file describe

2021-12-31 00:38 UTC, allwefantasy requested changes

2021-12-31 00:38 UTC, allwefantasy commented on streamingpro-it/src/test/resources/sql/simple/20_nesting_variables_across_cells_test.mlsql
> +!assert result ''':name=="ODS_T_TableName"'''  "The variable ods_table_name should be ODS_T_TableName";
The target table is not result

2021-12-31 08:31 UTC, closed without merging