add udf of crawler_http_with_header
byzer-org/byzer-lang pull request #1668
Opened 2022-01-18 03:39 UTC by hellozepp

## How to use `crawler_http`

crawler_http(url, method, map("k1","v1","k2","v2")) - Request url, return response result

## parameter：

method - supported POST/GET
map - key/value  

## Example

```
SELECT crawler_http_with_header("https://www.csdn.com", "get", map(), map("Authorization", "Bearer ${app_access_token}")) AS h AS content;
```

2022-01-18 03:44 UTC, allwefantasy commented
1. Can we use influent API instead of the original one?
2. Maybe we can change the UDF name at this time .

2022-01-18 03:44 UTC, allwefantasy commented
> * Can we use influent API instead of the original one?
> * Maybe we can change the UDF name at this time . For example: http? request?

2022-01-18 05:55 UTC, hellozepp commented
> 1. Can we use influent API instead of the original one?
> 2. Maybe we can change the UDF name at this time . For example: http? request?

---

yes,I will add another PR to replace with fluent.

2022-01-18 07:07 UTC, hellozepp commented
@chncaesar PTAL

2022-01-21 10:59 UTC, hellozepp commented
# Add new `rest_request` UDF

## Code Example
```
select rest_request( 
                        concat("https://open.XXX.cn/open-apis/contact/v3/departments/",
                               data.system_fields.department_id),
                        "GET", map(), map("Authorization", "Bearer ${app_access_token}"), map()) as content
         from viewRecord3
         group by data.system_fields.department_id
```

2022-01-21 11:06 UTC, chncaesar approved these changes

2022-01-21 13:32 UTC, allwefantasy requested changes

2022-01-21 13:32 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/crawler/udf/Functions.scala
> +    Stream.range(0, maxTries)
Use Scala way instead of Stream API in Java8.

2022-01-21 13:32 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/tech/mlsql/datasource/impl/MLSQLRest.scala
> +            if (config.path.endsWith("?")) config.path + "&" + urlParam else config.path + urlParam
The logical here is not right.

2022-01-21 13:32 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/crawler/udf/Functions.scala
> +class FunctionsUtils(override val uid: String) extends DslTool with  WowParams with Logging {
Should we remove the DslTool/WowParams trait here?  and the uid is not needed also.

2022-01-21 13:32 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/crawler/udf/Functions.scala
> +class FunctionsUtils(override val uid: String) extends DslTool with  WowParams with Logging {
Use object instead of class?

2022-01-21 13:32 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/crawler/udf/Functions.scala
> +      val func = new FunctionsUtils()
FunctionUtils should be object instead class is better?

2022-01-27 13:48 UTC, merged