#1657 Add python version detection function and call
byzer-org/byzer-lang pull request #1688
Opened 2022-02-11 07:48 UTC by kaliGo-Li

# What changes were proposed in this pull request?
- [ ] Finshed changes describe
make-distribution.sh add python version detection function and call.
# How was this patch tested?
- [ ] Testing done
<img width="566" alt="截屏2022-02-11 下午3 43 21" src="https://user-images.githubusercontent.com/70516188/153554372-75c46f43-0493-4410-99f8-43dc809ebf1f.png">
<img width="525" alt="截屏2022-02-11 下午3 43 56" src="https://user-images.githubusercontent.com/70516188/153554396-e4909fcf-1ce4-42d0-bc5e-1a9ae67763f6.png">

# Are there and DOC need to update?
- [ ] Doc is finished
Do not need to update DOC。
# Spark Core Compatibility

2022-02-11 07:53 UTC, hellozepp commented
@kaliGo-Li Please make sure to revert our dependencies to the `spark3` version.
You can specify MLSQL_SPARK_VERSION version as 3.0 when running `make-distribution.sh`.

2022-02-11 07:54 UTC, hellozepp requested changes

2022-02-11 07:54 UTC, hellozepp commented on external/mlsql-autosuggest/pom.xml
> +<!--         <scala.version>2.12.10</scala.version>  -->
Do not change the maven dependency version.

2022-02-11 07:57 UTC, hellozepp commented
@kaliGo-Li Can you use rebase to squeeze your multiple commits?

2022-02-11 08:06 UTC, hellozepp requested changes

2022-02-11 08:06 UTC, hellozepp commented on dev/make-distribution.sh
>      U_V1=`python -V 2>&1|awk '{print $2}'|awk -F '.' '{print $1}'`
Please use parameter names that are easy to understand

2022-02-11 08:06 UTC, hellozepp commented on dev/make-distribution.sh
> +    U_V3=`python -V 2>&1|awk '{print $2}'|awk -F '.' '{print $3}'`
Can you delete the two useless parameters U_V2, U_V2?

2022-02-14 05:07 UTC, hellozepp commented on dev/make-distribution.sh
Should we call this function `checkPython` ?

2022-02-14 05:19 UTC, hellozepp commented
@kaliGo-Li good job!  LGTM
@allwefantasy PTAL

2022-02-14 05:20 UTC, hellozepp commented
![image](https://user-images.githubusercontent.com/20615623/153804721-17708b45-db5d-41fe-8355-6b3f75eded2e.png)

2022-02-14 06:41 UTC, hellozepp approved these changes

2022-02-14 08:06 UTC, allwefantasy commented
LGTM

2022-02-14 08:09 UTC, allwefantasy approved these changes

2022-02-14 08:10 UTC, merged