Add the dev for it
byzer-org/byzer-lang pull request #1702
Opened 2022-02-24 12:07 UTC by hellozepp

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-02-27 13:06 UTC, allwefantasy approved these changes

2022-02-28 10:14 UTC, chncaesar requested changes
The ability  to run test cases on yarn is a major break through. 
However, current cases will not run for spark-3, if this pr is merged. 
Any difficulties blocking you from doing so?

2022-02-28 10:34 UTC, chncaesar approved these changes

2022-02-28 11:07 UTC, hellozepp commented
@chncaesar Yes, our test case is actually the business code that uses the modified framework. I plan to submit the framework part in this version, and the test case will be added later.

2022-03-01 01:26 UTC, merged