Byzer-lang invokes callback if Java UDf is not compilable
byzer-org/byzer-lang pull request #1705
Opened 2022-03-01 03:58 UTC by chncaesar

# What changes were proposed in this pull request?
“预”提交 PR，正式版 PR 会附上英文 。This is a pre-submit PR, English version will be provided in the follow-ups.

请各位指正代码代码修复是否有问题：RuntimeCompileUDF.generateFunction 是否是最佳方式。下面是分析过程。

## 问题
### Java UDF 声明和使用

```sql
REGISTER ScriptUDF.`` AS echoFun WHERE 
and lang="java"
and udfType="udf"
and className="Test"
and methodName="test"
and code='''
import java.util.HashMap;
import java.util.Map;
public class Test {
    public Map<String, String> test(String s) {
      Map m = new HashMap<>();
      m.put(s, s);
      return m
  }
}
''';

select echoFun("a") as output;
```

这是一个无法编译的 Java UDF，13 行结尾遗漏了 ; 。 我们期望 Notebook 停止运行，并告知用户发生错误。但是当前版本 Byzer-lang 2.3.0-SNAPSHOT，无法处理 Error，导致Job 一直处于运行状态。

### 原因分析
异常堆栈（为保持简洁有删减 ）结合代码可以找到原因：
```text
Exception in thread "pool-23-thread-5" tech.mlsql.common.utils.concurrent.ExecutionError: java.lang.ClassFormatError: Truncated class file
        at tech.mlsql.common.utils.cache.LocalCache$Segment.get(LocalCache.java:2157)
        at streaming.udf.RuntimeCompileScriptInterface.driverExecute(RuntimeCompileScriptInterface.scala:39)        
        at streaming.udf.JavaRuntimeCompileUDF$.argumentNum(JavaRuntimeCompileUDF.scala:29)        
        at streaming.udf.RuntimeCompileUDF.generateFunction(RuntimeCompileUDF.scala:52)        
        at streaming.udf.JavaRuntimeCompileUDF$.generateFunction(JavaRuntimeCompileUDF.scala:13)
        at streaming.udf.RuntimeCompileUDF.udf(RuntimeCompileUDF.scala:57)        
        at streaming.udf.JavaRuntimeCompileUDF$.udf(JavaRuntimeCompileUDF.scala:13)
        at streaming.dsl.mmlib.algs.ScriptUDF.$anonfun$load$8(ScriptUDF.scala:93)
        at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry.lookupFunction(FunctionRegistry.scala:121)      
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)        
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
        at tech.mlsql.dsl.adaptor.SelectAdaptor.parse(SelectAdaptor.scala:73)        
        at streaming.dsl.ScriptSQLExec$._parse(ScriptSQLExec.scala:160)        
        at streaming.rest.RestController.$anonfun$script$1(RestController.scala:153)       
```

Java UDF 调用时分为三步：用户调用 UDF --> 编译UDF --> 执行 UDF 。编译时，从 LocalCache 读取源代码，调用 tools.jar 的类库编译，最后 ClassLoader 加载字节码。

具体到这个例子，编译 UDF 时发生 ExecutionError
```Java
public class ExecutionError extends Error 
```

目前  /run/script/ 代码链路缺乏 Error 处理逻辑，不调用 Notebook 回调，直接进入 finally 块。

### 修复方式：
捕获EecutionError, 转换为 RuntimeException, 使得 RestController 能调用 callback 。

# How was this patch tested?
- Not finished

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-03-01 04:13 UTC, hellozepp requested changes

2022-03-01 04:13 UTC, hellozepp commented on streamingpro-core/src/main/java/streaming/udf/RuntimeCompileUDF.scala
> +    }
如果是其他异常，这里可能会得到一个case匹配不到的异常

2022-03-01 04:13 UTC, hellozepp commented on streamingpro-core/src/main/java/streaming/udf/RuntimeCompileUDF.scala
> +      case e: ExecutionError => throw new RuntimeException(e.getCause)
是否可以添加单测覆盖这个case

2022-03-01 07:30 UTC, chncaesar commented on streamingpro-core/src/main/java/streaming/udf/RuntimeCompileUDF.scala
> +    }
已测试，其他不匹配的异常，直接抛出。

2022-03-01 07:30 UTC, chncaesar commented on streamingpro-core/src/main/java/streaming/udf/RuntimeCompileUDF.scala
> +      case e: ExecutionError => throw new RuntimeException(e.getCause)
单测在后面补上。

2022-03-02 03:21 UTC, allwefantasy approved these changes

2022-03-02 03:28 UTC, hellozepp approved these changes

2022-03-02 03:33 UTC, merged