Update LexerUtils.scala
byzer-org/byzer-lang pull request #1727
Opened 2022-03-27 19:01 UTC by kaliGo-Li

# What changes were proposed in this pull request?
- [ ] Finshed changes describe
Optimized the logic of LexerUtils.scala for blank line judgment.
When the last word on the previous line of the cursor is ";", the complex judgment logic that follows will no longer be executed.
# How was this patch tested?
- [ ] Testing done
<img width="1060" alt="截屏2022-03-28 02 56 56" src="https://user-images.githubusercontent.com/70516188/160296413-a47ff927-8541-4a1b-b591-0217ed4631e5.png">
<img width="961" alt="截屏2022-03-28 02 57 06" src="https://user-images.githubusercontent.com/70516188/160296424-1ad186ad-e2da-4871-abc1-743b627e0d37.png">
<img width="942" alt="截屏2022-03-28 02 57 33" src="https://user-images.githubusercontent.com/70516188/160296434-65078e52-18f1-487e-b896-eebd734f245d.png">

There are two states: no code below the cursor and code below the cursor.
If the last word of the line above the cursor is ";", then the semantics of the statement is considered to end, and TokenPos(-1, TokenPosType.NEXT, -1) is returned.

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-03-28 04:13 UTC, hellozepp requested changes

2022-03-28 04:13 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +    var flag:Boolean = false
不要使用flag这种无具体含义的命名

2022-03-28 04:13 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +    var lineNumLast:Int = 0
我们应该尽量减少过多的中间变量声明

2022-03-28 04:13 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +    var lineNumLast:Int = 0
这里可以直接使用104行的lastToken，不用再写逻辑区分是否为最后一行

2022-03-28 04:13 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +      case true => if(oneLineTokens.isEmpty && tokens(lineNumLast).getType == DSLWrapper.SEMICOLON) {
同理，不用再写逻辑区分是否为最后一行

另外，改成上述写法可以避免tokens(lineNumLast)这个o(n)的调用

2022-03-28 04:18 UTC, hellozepp commented
@kaliGo-Li 请为上述的修改添加详实的单测，确保单测可以覆盖修改内容

2022-03-28 15:35 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +    var flag:Boolean = false
这里还没改吗

2022-03-29 02:06 UTC, hellozepp commented on external/mlsql-autosuggest/src/test/java/com/intigua/antlr4/autosuggest/LexerUtilsTest.scala
> +    assert(items.map(_.name) == List("table1", "table2", "aa", "bb", "cc", "a", "b", "c", "count", "split"))
这里单测没有成功，修复一下。

2022-03-30 15:55 UTC, hellozepp commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +   *In this method, three states of the cursor are judged in the code.
*前应该有空格

2022-03-30 15:58 UTC, kaliGo-Li commented on external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala
> +   *In this method, three states of the cursor are judged in the code.
ok

2022-04-21 05:33 UTC, hellozepp approved these changes

2022-04-21 06:48 UTC, chncaesar approved these changes

2022-04-21 09:58 UTC, merged