change byzer package naming
byzer-org/byzer-lang pull request #1732
Opened 2022-04-01 14:18 UTC by hellozepp

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-04-02 00:42 UTC, chncaesar requested changes

2022-04-02 00:42 UTC, chncaesar commented on docs/gitbook/v1/howtouse/k8s_deploy.md
> -            local:///tmp/streamingpro-mlsql-spark_3.0_2.12-1.7.0-SNAPSHOT.jar
Please change byzer-lang version 1.7.0-SNAPSHOT to 2.2.2

2022-04-02 00:42 UTC, chncaesar commented on external/mlsql-autosuggest/pom.xml
> +        <version>2.2.3-SNAPSHOT</version>
Next version should be 2.3.0-SNAPSHOT.

2022-04-07 05:46 UTC, chncaesar approved these changes

2022-04-07 05:46 UTC, chncaesar commented on streamingpro-assembly/pom.xml
> +        <finalName>byzer-lang-${spark.version}-${project.version}</finalName>
To Change mlsql-engine main jar to byzer-lang , please follow this code in assembly.xml:
```
    <files>
    <file>
        <source>${project.parent.basedir}/streamingpro-mlsql/target/streamingpro-mlsql-spark_${spark.bigversion}_${scala.binary.version}-${project.version}.jar</source>
        <outputDirectory>main</outputDirectory>
        <destName>byzer-lang-${spark.bigversion}_${scala.binary.version}-${project.version}.jar</destName>
    </file>
    </files>
```

And remove moduleSets
```
<!--    <moduleSets>-->
<!--        <moduleSet>-->
<!--            &lt;!&ndash; Enable access to all projects in the current multimodule build! &ndash;&gt;-->
<!--            <useAllReactorProjects>true</useAllReactorProjects>-->

<!--            &lt;!&ndash; Now, select which projects to include in this module-set. &ndash;&gt;-->
<!--            <includes>-->
<!--                <include>tech.mlsql:streamingpro-mlsql-spark_${spark.bigversion}_${scala.binary.version}</include>-->
<!--            </includes>-->
<!--            <excludes>-->
<!--&lt;!&ndash;                <exclude>tech.mlsql:streamingpro-common-${spark.bigversion}_${scala.binary.version}</exclude>&ndash;&gt;-->
<!--&lt;!&ndash;                <exclude>tech.msql:streamingpro-dl4j</exclude>&ndash;&gt;-->
<!--            </excludes>-->
<!--            <binaries>-->
<!--                <outputDirectory>libs</outputDirectory>-->
<!--                <includeDependencies>false</includeDependencies>-->
<!--                <unpack>false</unpack>-->
<!--            </binaries>-->
<!--        </moduleSet>-->
<!--    </moduleSets>-->
```

2022-04-07 05:48 UTC, hellozepp commented
![erQClD7oRJ](https://user-images.githubusercontent.com/20615623/162129051-c4d3ad83-410e-449a-862c-aadc11200794.png)

2022-04-10 20:52 UTC, merged