Add multi file upload support
byzer-org/byzer-lang pull request #1736
Opened 2022-04-02 07:54 UTC by anan0120

# What changes were proposed in this pull request?
- [ ] Add multi file upload support

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-04-05 09:05 UTC, chncaesar commented
Issue #1737

2022-04-13 07:59 UTC, chncaesar requested changes

2022-04-13 07:59 UTC, chncaesar commented on streamingpro-mlsql/src/main/java/tech/mlsql/datasource/impl/MLSQLRest.scala
> +        request.body(entity.build()).execute()      case (_, v) =>
case (_, v) => 需要换行

2022-04-13 07:59 UTC, chncaesar commented on streamingpro-mlsql/src/test/scala/streaming/test/Test.scala
> -            |{"key":"yes","value":"no","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
Please add unit test to MLSQLRestTest

2022-04-20 03:38 UTC, anan0120 commented
1、case (_, v) => 需要换行    已处理
2、无法进行mock，程序中有实际路径的判断

2022-04-21 05:17 UTC, hellozepp commented on streamingpro-mlsql/src/main/java/tech/mlsql/datasource/impl/MLSQLRest.scala
> +        request.removeHeaders("Content-Type") // Avoid setting boundary
请不要使用代码结尾注释，添加到该行的上面

2022-04-21 05:22 UTC, hellozepp commented
@anan0120 你可以添加一个测试脚本用例到byzer-lang/streamingpro-it/src/test/resources/sql/yarn下面吗，可以参考例子aes_encrypt.mlsql

2022-04-21 05:26 UTC, hellozepp requested changes

2022-04-21 05:26 UTC, hellozepp commented on streamingpro-mlsql/src/test/scala/streaming/test/Test.scala
> +            |{"key":"yesvalue","value":"no","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
这个修改是必要的吗

2022-04-21 05:52 UTC, anan0120 commented on streamingpro-mlsql/src/test/scala/streaming/test/Test.scala
> +            |{"key":"yesvalue","value":"no","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
这个确实没必要修改，当时做了临时的一个测试，遗留到了这次PR上

2022-04-21 06:42 UTC, anan0120 commented on streamingpro-mlsql/src/test/scala/streaming/test/Test.scala
> +            |{"key":"yesvalue","value":"no","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
已复原

2022-04-21 06:42 UTC, anan0120 commented on streamingpro-mlsql/src/main/java/tech/mlsql/datasource/impl/MLSQLRest.scala
> +        request.removeHeaders("Content-Type") // Avoid setting boundary
已调整

2022-04-21 06:44 UTC, chncaesar approved these changes

2022-04-23 15:46 UTC, hellozepp approved these changes

2022-04-23 15:46 UTC, merged