#1804 support skip first N lines for csv reader
byzer-org/byzer-lang pull request #1805
Opened 2022-08-05 03:18 UTC by ckeys

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-08-06 05:23 UTC, allwefantasy requested changes

2022-08-06 05:23 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/impl/MLSQLCSV.scala
> +    val df = reader.options(rewriteConfig(config.config)).format(format).load(resourceRealPath(context.execListener, Option(owner), config.path))
这个df 是不是不是必要的？

2022-08-08 03:24 UTC, fishcus commented on streamingpro-core/src/main/java/tech/mlsql/tool/HDFSOperatorV2.scala
> +    val writePathParts = pathElements.take(pathElements.length - 1) :+ System.currentTimeMillis().toString
writePathParts 带上 skipFirstNLines的信息吗？ 这样是否可以不用每次都写一份临时文件，skipFirstNLines值一样的情况下，如果已经写了一份，可以直接读

2022-08-08 03:25 UTC, fishcus commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/impl/MLSQLCSV.scala
> +    val skipFirstNLines = config.config.get("skipFirstNLines")
df 参数没有被使用的，应该不需要吧

2022-08-08 04:08 UTC, allwefantasy requested changes

2022-08-08 04:08 UTC, allwefantasy commented on streamingpro-core/src/main/java/streaming/core/datasource/MLSQLBaseFileSource.scala
>  abstract class MLSQLBaseFileSource extends MLSQLSource with MLSQLSink with MLSQLSourceInfo with MLSQLRegistry with DslTool {
另外，能不能把父类的这些代码都迁移到 MLSQLCSV 里。 我觉得抽象应该还自下向上的。也就是当我们发现多个数据源都确实需要这个功能后，再往上提到父类。而不是觉得可能需要，就放到父类，会导致父类代码越来越复杂。

2022-08-08 09:50 UTC, fishcus approved these changes

2022-08-09 11:26 UTC, allwefantasy approved these changes

2022-08-09 11:27 UTC, allwefantasy commented
再次确认下，在本地 Notebook 中测试通过了对吧？ 另外，当前这个功能是没有测试代码的，相关的测试功能能不能安排在下一个sprint中？

2022-08-09 13:09 UTC, merged