Render error message using config file
byzer-org/byzer-lang pull request #1814
Opened 2022-08-10 17:20 UTC by chncaesar

# What changes were proposed in this pull request?
#1806 

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-08-11 03:09 UTC, allwefantasy requested changes

2022-08-11 03:09 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/rest/RestController.scala
> +                val msg = ExceptionRenderManager.call(e).str.getOrElse( e.getMessage )
这里破坏了原有的输出格式。考虑下如果没有安装你的插件 你现在的修改就导致行为变化了

2022-08-11 03:11 UTC, allwefantasy requested changes

2022-08-11 03:11 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/rest/RestController.scala
> -        val msg = ExceptionRenderManager.call(e)
这边的代码似乎没必要修改？ 其次 对于异步会不会导致你的插件被调用两次？

2022-08-11 03:26 UTC, fishcus commented on conf/err-msg-template.json
> +  { "regexp": "MLSQL Parser error in .*?", "msg": "MLSQL Parser error"}
这个配置文件放到byzer-lang？ 还是在extension？

2022-08-11 04:02 UTC, allwefantasy commented on conf/err-msg-template.json
> +  { "regexp": "MLSQL Parser error in .*?", "msg": "MLSQL Parser error"}
应该是要放 extension里。extension里应该有个查找规则，比如先看用户有没有指定绝对路径，接着在当前项目的 conf目录下找。

2022-08-11 04:02 UTC, allwefantasy commented on conf/err-msg-template.json
> +  { "regexp": "MLSQL Parser error in .*?", "msg": "MLSQL Parser error"}
> 这个配置文件放到byzer-lang？ 还是在extension？

应该是要放 extension里。extension里应该有个查找规则，比如先看用户有没有指定绝对路径，接着在当前项目的 conf目录下找。

2022-08-12 02:26 UTC, chncaesar commented on streamingpro-mlsql/src/main/java/streaming/rest/RestController.scala
> +                val msg = ExceptionRenderManager.call(e).str.getOrElse( e.getMessage )
这里应该不会，如果 不配置新 插件， `ExceptionRenderManager.call(e) `  中有 `DefaultExceptionRender` 兜底，它的逻辑和删掉的代码是一样的。

2022-08-12 06:22 UTC, chncaesar commented on streamingpro-mlsql/src/main/java/streaming/rest/RestController.scala
> -        val msg = ExceptionRenderManager.call(e)
讨论后结论：不会被调用两次。

2022-08-12 06:27 UTC, chncaesar commented on conf/err-msg-template.json
> +  { "regexp": "MLSQL Parser error in .*?", "msg": "MLSQL Parser error"}
配置文件目录查找顺序：
1. 用户指定的目录
2. byzer-lang/conf  目录
3. 插件 jar 包

2022-08-12 10:29 UTC, allwefantasy requested changes

2022-08-12 10:29 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/rest/RestController.scala
> +      context.addEnv("show_stack", param("show_stack", "false"))
插件里想要获得这个参数可以通过 context.userDefinedParam("__PARAMS__")("show_stack") 获取。 参考第 319 行代码。

2022-08-13 10:00 UTC, allwefantasy approved these changes

2022-08-13 13:50 UTC, fishcus approved these changes

2022-08-15 01:50 UTC, merged