修复剖析测试报错
byzer-org/byzer-lang pull request #1881
Opened 2022-11-21 11:30 UTC by hellozepp

# What changes were proposed in this pull request?
- [ ] Finshed changes describe

# How was this patch tested?
- [ ] Testing done

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

2022-11-21 12:31 UTC, allwefantasy requested changes

2022-11-21 12:31 UTC, allwefantasy commented on streamingpro-core/src/main/java/tech/mlsql/dsl/CommandCollection.scala
> +  def register(name: String, value: String): String = commandMapping.put(name, value)
`register` can be replaced by function `refreshCommandMapping`

2022-11-22 02:54 UTC, hellozepp commented on streamingpro-core/src/main/java/tech/mlsql/dsl/CommandCollection.scala
> +  def register(name: String, value: String): String = commandMapping.put(name, value)
refreshCommandMapping is to register multiple values

2023-01-29 12:03 UTC, allwefantasy approved these changes

2023-01-29 12:03 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/core/datasource/impl/MLSQLJDBC.scala
> +        url = options.get("url")
这部分代码是不是应该直接在异常里检测？另外单独增加一个hive的的异常似乎显得不够？

2023-01-30 01:17 UTC, merged