新增ModelExplainInPlace模块
byzer-org/byzer-lang pull request #299
Opened 2018-06-24 08:42 UTC by wuheyi

2018-06-24 10:19 UTC, allwefantasy requested changes

2018-06-24 10:19 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/TrainAdaptor.scala
> +    "ModelExplainInPlace" -> "streaming.dsl.mmlib.algs.SQLModelExplainInPlace",
这里不需要添加了。可以去掉。参看[PR285](https://github.com/allwefantasy/streamingpro/pull/285)

2018-06-24 10:19 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    df.sparkSession.read.json("/tmp/attributes.json")
你这个是本机测试成功，在实际线上环境不会work.另外如果并发执行，就会同时写入这个路径，那么得到的结果是不正确的。正确的做法应该是： 1.在/tmp/__mlsql__下生成一个随机(uuid)目录，参看SQLPythonFunc中的路径辅助函数，之后传递给ExtrernalCommandRunner，在python脚本中获取该路径，然后写入,之后在scala里然后再将该目录上传到hdfs上，最后读取并且返回dataframe.

2018-06-24 10:19 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +  override def load(sparkSession: SparkSession, path: String, params: Map[String, String]): Any = {
不支持register的话，可以抛出一个异常。

2018-06-24 10:19 UTC, allwefantasy commented on streamingpro-mlsql/src/main/resources-local/python/mlsql_sk_attributes.py
> +clf = svm.SVC()
这个显然不具备通用性，应该是可以加载任何模型的。

2018-06-24 10:22 UTC, wuheyi commented on streamingpro-mlsql/src/main/java/streaming/dsl/TrainAdaptor.scala
> +    "ModelExplainInPlace" -> "streaming.dsl.mmlib.algs.SQLModelExplainInPlace",
我最开始是没加的，按照你之前说的,前缀是SQL，后缀是InPlace；
但是会报错，就重新在这里加上了配置。。

2018-06-24 10:23 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/TrainAdaptor.scala
> +    "ModelExplainInPlace" -> "streaming.dsl.mmlib.algs.SQLModelExplainInPlace",
可以给我提Issue,我来fix.

2018-06-24 10:25 UTC, wuheyi commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    df.sparkSession.read.json("/tmp/attributes.json")
明白啦，我修改下

2018-06-24 10:27 UTC, wuheyi commented on streamingpro-mlsql/src/main/resources-local/python/mlsql_sk_attributes.py
> +clf = svm.SVC()
这个代码是我用于测试的，忘记删掉了
模型我是通过modelPath参数传入，支持任意模型

2018-06-24 10:34 UTC, allwefantasy commented on streamingpro-mlsql/src/main/resources-local/python/mlsql_sk_attributes.py
> +clf = svm.SVC()
Ok，签名改完我会再check下

2018-06-24 15:31 UTC, cfmcgrady commented on docs/mlsql-data-processing-model.md
> +
这个格式是有问题的，文档最好可以先自己看一下，是否排版有问题。

2018-06-24 15:31 UTC, cfmcgrady commented on streamingpro-mlsql/src/test/scala/streaming/core/AutoMLSpec.scala
> +      spark.sql("select * from parquet.`/tmp/william/tmp/modelExplainInPlace/data`").show(100, false)
unittest是需要断言的，像这种最好可以写成example。

2018-06-24 15:31 UTC, cfmcgrady commented on docs/mlsql-data-processing-model.md
> +train traindataframe as ConfusionMatrix.`/Users/dxy_why/tmp/modelExplainInPlace/`
这样写是误导别人呀！！！

2018-06-24 15:31 UTC, cfmcgrady commented on docs/mlsql-data-processing-model.md
> +select  * from parquet.`/Users/dxy_why/tmp/modelExplainInPlace/data`
这个是否可以设计成用户自定义输出路径，否则给个默认路径，且在使用文档中详细说明。

2018-06-25 01:54 UTC, wuheyi commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +  override def load(sparkSession: SparkSession, path: String, params: Map[String, String]): Any = {
后续抛出Runtime异常

2018-06-25 01:59 UTC, allwefantasy commented on streamingpro-mlsql/src/main/resources-local/python/mlsql_sk_attributes.py
> +clf = svm.SVC()
另外，正式发布的时候，需要在resources-online里也添加该python文件。否则线上会提示找不到文件。

2018-06-25 02:16 UTC, wuheyi commented on docs/mlsql-data-processing-model.md
> +train traindataframe as ConfusionMatrix.`/Users/dxy_why/tmp/modelExplainInPlace/`
这里写错了

2018-06-25 02:17 UTC, wuheyi commented on docs/mlsql-data-processing-model.md
> +select  * from parquet.`/Users/dxy_why/tmp/modelExplainInPlace/data`
这里是支持自定输出路径的，文档我更新下

2018-06-25 02:17 UTC, wuheyi commented on docs/mlsql-data-processing-model.md
> +
排版有误，我修改下

2018-06-25 02:44 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    val ExternalCommandRunnerDataframe = Seq("aaa").toDF("test")
可以弄一个空或者一个看得懂的变量，toDF也是。

2018-06-25 02:48 UTC, allwefantasy requested changes

2018-06-25 02:48 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +      //模型保存到hdfs上
res.foreach还是要的，否则不会有任何异常或者错误。

2018-06-25 02:48 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    })
map 需要count出发执行？

2018-06-25 02:48 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    throw new RuntimeException("predict method is not supported!")
register is not supported by this module now.

2018-06-25 02:58 UTC, wuheyi commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    })
已经用count触发

2018-06-25 03:01 UTC, allwefantasy commented on streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLModelExplainInPlace.scala
> +    val ExternalCommandRunnerDataframe = Seq("").toDF("test")
model_expalin_inplace_field

2018-06-25 03:03 UTC, allwefantasy approved these changes

2018-06-25 03:09 UTC, merged