文档调整
byzer-org/byzer-lang pull request #498
Opened 2018-09-05 08:35 UTC by CoderOverflow

文档调整

2018-09-07 06:24 UTC, allwefantasy reviewed
Can you merge all this commits to one commit then invoke PR?

2018-09-07 06:24 UTC, allwefantasy commented on README.md
> +2.1 unarvhive the Apache Spark 2.2.0 package
We can show clearly that these steps are optional cause we can use  full path e.g.  ./[your-spark-home]/bin/submit ...  to submit our application.

2018-09-07 06:27 UTC, allwefantasy requested changes

2018-09-07 06:27 UTC, allwefantasy commented on README.md
> +    add following sentences at the end of the file
o

2018-09-10 02:12 UTC, CoderOverflow commented
OK， let me try  ：）

2018-09-10 02:13 UTC, closed without merging